/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.practica.promptzal.Frontend;

import com.practica.promptzal.Backend.lexer.Token;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wilian
 */
public class TablaTokens extends javax.swing.JInternalFrame {

   private DefaultTableModel modeloTabla;

    public TablaTokens() {
        initComponents();
        configurarTabla();
    }

    private void configurarTabla() {

        modeloTabla = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "No.",
                    "Lexema",
                    "Tipo",
                    "Fila",
                    "Columna"
                }
        ) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        jTable1.setModel(modeloTabla);
    }

    public void cargarTokens(List<Token> tokens) {

        modeloTabla.setRowCount(0);

        if (tokens == null) {
            return;
        }

        for (Token token : tokens) {

            modeloTabla.addRow(new Object[]{
                token.getNumero(),
                token.getLexema(),
                token.getTipo(),
                token.getFila(),
                token.getColumna()
            });
        }
    }

    public void limpiarTabla() {

        modeloTabla.setRowCount(0);
    }

    public javax.swing.JTable getTabla() {

        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Lexerma", "Tipo", " Fila", "Columna"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
