/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.practica.promptzal.Frontend;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wilian
 */
public class TablaEstadisticas extends javax.swing.JInternalFrame {

   private DefaultTableModel modeloTabla;
   
    public TablaEstadisticas() {
        initComponents();
        configurarTabla();
    }
    
     private void configurarTabla() {

        modeloTabla = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Estadística",
                    "Valor"
                }
        ) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        jTable1.setModel(modeloTabla);
    }

    public void cargarEstadisticas(
            int totalTokens,
            int totalErrores,
            int totalLineas) {

        modeloTabla.setRowCount(0);

        modeloTabla.addRow(new Object[]{
            "Total de tokens",
            totalTokens
        });

        modeloTabla.addRow(new Object[]{
            "Total de errores",
            totalErrores
        });

        modeloTabla.addRow(new Object[]{
            "Total de líneas",
            totalLineas
        });
    }

    public void agregarEstadistica(
            String nombre,
            Object valor) {

        if (nombre == null || nombre.isEmpty()) {
            return;
        }

        modeloTabla.addRow(new Object[]{
            nombre,
            valor
        });
    }

    public void limpiarTabla() {

        modeloTabla.setRowCount(0);
    }

    public javax.swing.JTable getTabla() {

        return jTable1;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
